### PR TITLE
[RFC][2.0] rewrite version detection

### LINKED ISSUE #152: remove stable flag and implement better validation to prevent duplicate declaration issues
The ``version => stable`` flag was used during the ``0.x`` series due to the fact that every second version was stable (``0.10`` was stable, ``0.11`` is not).
The only 0.x version we support is ``0.12`` and this one is a stable one, so the current behavior is simply wrong.

Therefore I recommend the following:

- `latest` for the latest version
- `lts` for the latest LTS version
- `5' for the latest 5.x release, `6` for the latest 6.x release

`stable` will be dropped since it's a relict when the `0.x` series was the current one.

Furthermore it should be evaluated whether to use the SemVer library of ruby rather than those bloated regexes in the ``nodejs_functions.rb``.

To avoid odd ``duplicate declaration`` errors, the installer should also check for version conflicts.

### PR DESCRIPTION
**Pull request by Ma27**
### Overview

This PR includes heavy changes (:warning: will be one of the bigger BC breaks) concerning the version detection:

- use `https://nodejs.org/dist/index.json` for version analysation rather than parsing the HTML of the apache default page rendered in `https://nodejs.org/dist`
- dropped `stable` as it's a relict of the ancient `0.x` series (see #152 for more information)
- introduced an `lts` keyword for fetching the latest LTS release
- introduced support for generic versions (``5.x`` installs the latest NodeJS 5 release, ``5.5`` installs the latest NodeJS 5.5.x release)
- joined ``nodejs_*_version`` functions into a big function to avoid unnecessary if/else conditions in the Puppet DSL
- it's possible now to omit the `v` prefix for versions (e.g. `6.3.1` installs the appropriate release ``v6.3.1``)

### Related issues

resolves #152

### CODE REVIEW

File: lib/puppet/parser/functions/evaluate_version.rb [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+      end
+
+      return version
+    end
+
+    if version =~ /^(?:(v)?)[0-9]+\.([0-9]+|x)$/
+      return get_version_from_branch version
+    end
+
+    raise Puppet::ParseError, "evaluate_version(): version must be `lts`, `latest` or look like `x.x.x`"
```
Comment (Ma27) [inline lib/puppet/parser/functions/evaluate_version.rb]: the exception message is not detailed enough concerning the generic versions. This should be improved.

File: README.md [hunk 2]
```diff
@@ -54,25 +54,46 @@ class { 'nodejs':
...
 
 ### Setup using the pre-built installer
 
-To use the pre-built installer version provided via https://nodejs.org/download you have to set `make_install` to `false`
+To use the pre-built installer version provided via https://nodejs.org/download you have to set `make_install` to `false`.
 
 ```puppet
 class { 'nodejs':
-  version      => 'stable',
+  version      => 'lts',
```
Comment (Ma27) [inline README.md]: I think this change should be done everywhere

File: README.md [hunk 3]
```diff
@@ -54,25 +54,46 @@ class { 'nodejs':
...
 This will compile and install Node.js version `v6.0.0` to your machine. `node` and `npm` will be available in your `$PATH` via `/usr/local/node/node-default/bin` so you can just start using `node`.
 
-Shortcuts are provided to easily install the `latest` or `stable` release by setting the `version` parameter to `latest` or `stable`. It will automatically look for the last release available on https://nodejs.org.
+Shortcuts are provided to easily install the `latest` release or the latest LTS release (`lts`) by setting the `version` parameter to `latest` or `lts`. It will automatically look for the last release available on https://nodejs.org.
 
 ```puppet
 class { 'nodejs':
-  version => 'stable',
+  version => 'latest',
 }
```
Comment (Ma27) [inline README.md]: might be useful to add a code example for installing the LTS release.

File: lib/puppet/parser/functions/evaluate_version.rb [hunk 4]
```diff
@@ -0,0 +1,32 @@
+require_relative 'util/nodejs_functions'
+
+module Puppet::Parser::Functions
+  newfunction(:evaluate_version, :type => :rvalue) do |args|
+    raise(Puppet::ParseError, "evaluate_version(): too few arguments") if args.size < 1
+
+    version = args[0]
+    if version == 'latest'
+      return get_latest_version
+    end
```
Comment (Ma27) [inline lib/puppet/parser/functions/evaluate_version.rb]: simplify to `return get_latest_version if version == 'latest'

File: lib/puppet/parser/functions/evaluate_version.rb [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+
+    if version == 'lts'
+      return get_lts_version
+    end
```
Comment (Ma27) [inline lib/puppet/parser/functions/evaluate_version.rb]: same as with the latest version

File: lib/puppet/parser/functions/evaluate_version.rb [hunk 6]
```diff
@@ -0,0 +1,32 @@
...
+
+    if version =~ /^(?:(v)?)[0-9]+\.[0-9]+\.[0-9]+/
+      # if the version is matched, but contains no `v` as prefix, it will
+      # be added automatically
+      if version =~ /^[^v](.*)/
+        return 'v' + version
+      end
```
Comment (Ma27) [inline lib/puppet/parser/functions/evaluate_version.rb]: same as with lts and latest version

File: lib/puppet/parser/functions/evaluate_version.rb [hunk 7]
```diff
@@ -0,0 +1,32 @@
...
+
+      return version
+    end
+
+    if version =~ /^(?:(v)?)[0-9]+\.([0-9]+|x)$/
+      return get_version_from_branch version
+    end
```
Comment (Ma27) [inline lib/puppet/parser/functions/evaluate_version.rb]: same as with lts and latest version

File: lib/puppet/parser/functions/util/nodejs_functions.rb [hunk 8]
```diff
@@ -49,23 +51,36 @@ def get_version_list
...
+    regex = /^v#{version}\.[0-9]+\.[0-9]+$/
+  else
+    regex = /^v#{version}\.([0-9]+)$/ 
+  end
+
+  version_data = get_version_list
+    .map { |o| o['version'] }
+    .select { |v| v =~ regex }
+
+  version_data.first
```
Comment (Ma27) [inline lib/puppet/parser/functions/util/nodejs_functions.rb]: not sure, but it might be better to put everything into a class, make all the above stuff private and those for methods are the public API.

File: manifests/init.pp [hunk 9]
```diff
@@ -29,7 +29,7 @@
 #  }
 #
 class nodejs(
-  $version        = 'stable',
+  $version        = 'latest',
```
Comment (Ma27) [inline manifests/init.pp]: I think `lts` is the better option

**Comment by Ma27** [comment]
added `delayed` label as I'll keep it open for a bit now.

**Comment by willdurand** [comment]
Could not agree more with all of these changes! Awesome work @Ma27

File: README.md (hunk 2 above)
Comment (Ma27) [inline README.md]: done

**Comment by Ma27** [comment]
will merge this now. When a first alpha is about to come, I'll publish a changelog...
